# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dicomtreeQT5.ui',
# licensing of 'dicomtreeQT5.ui' applies.
#
# Created: Mon Nov 25 15:43:08 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DCMTreeForm(object):
    def setupUi(self, DCMTreeForm):
        DCMTreeForm.setObjectName("DCMTreeForm")
        DCMTreeForm.resize(800, 600)
        DCMTreeForm.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(DCMTreeForm)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, 2, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fsearchbar = QtWidgets.QFrame(self.centralwidget)
        self.fsearchbar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fsearchbar.sizePolicy().hasHeightForWidth())
        self.fsearchbar.setSizePolicy(sizePolicy)
        self.fsearchbar.setMinimumSize(QtCore.QSize(0, 32))
        self.fsearchbar.setMaximumSize(QtCore.QSize(16777215, 32))
        self.fsearchbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fsearchbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fsearchbar.setObjectName("fsearchbar")
        self.widget = QtWidgets.QWidget(self.fsearchbar)
        self.widget.setGeometry(QtCore.QRect(2, 2, 781, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.qle_filter_tag = QtWidgets.QLineEdit(self.widget)
        self.qle_filter_tag.setClearButtonEnabled(True)
        self.qle_filter_tag.setObjectName("qle_filter_tag")
        self.horizontalLayout.addWidget(self.qle_filter_tag)
        self.verticalLayout.addWidget(self.fsearchbar)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.treeView.setFont(font)
        self.treeView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeView.setAcceptDrops(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeView.setAlternatingRowColors(False)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        DCMTreeForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DCMTreeForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        DCMTreeForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DCMTreeForm)
        self.statusbar.setObjectName("statusbar")
        DCMTreeForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DCMTreeForm)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        DCMTreeForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtWidgets.QAction(DCMTreeForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/ImageOpen.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit = QtWidgets.QAction(DCMTreeForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/exit.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(DCMTreeForm)
        self.action_About.setObjectName("action_About")
        self.action_Save = QtWidgets.QAction(DCMTreeForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/ImageSave.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon2)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(DCMTreeForm)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_Insert = QtWidgets.QAction(DCMTreeForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/add.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Insert.setIcon(icon3)
        self.action_Insert.setObjectName("action_Insert")
        self.action_Edit = QtWidgets.QAction(DCMTreeForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/edit.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Edit.setIcon(icon4)
        self.action_Edit.setObjectName("action_Edit")
        self.action_Delete = QtWidgets.QAction(DCMTreeForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/del.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon5)
        self.action_Delete.setObjectName("action_Delete")
        self.actionSelect_All = QtWidgets.QAction(DCMTreeForm)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.action_Copy = QtWidgets.QAction(DCMTreeForm)
        self.action_Copy.setObjectName("action_Copy")
        self.actionClear_selection = QtWidgets.QAction(DCMTreeForm)
        self.actionClear_selection.setObjectName("actionClear_selection")
        self.action_Find_tag = QtWidgets.QAction(DCMTreeForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/search.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Find_tag.setIcon(icon6)
        self.action_Find_tag.setObjectName("action_Find_tag")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_About)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menu_Edit.addAction(self.actionClear_selection)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Find_tag)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Insert)
        self.menu_Edit.addAction(self.action_Edit)
        self.menu_Edit.addAction(self.action_Delete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Insert)
        self.toolBar.addAction(self.action_Edit)
        self.toolBar.addAction(self.action_Delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Find_tag)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(DCMTreeForm)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("triggered()"), DCMTreeForm.close)
        QtCore.QMetaObject.connectSlotsByName(DCMTreeForm)

    def retranslateUi(self, DCMTreeForm):
        DCMTreeForm.setWindowTitle(QtWidgets.QApplication.translate("DCMTreeForm", "Dicom Tree Viewer", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Filter DICOM tags:", None, -1))
        self.qle_filter_tag.setPlaceholderText(QtWidgets.QApplication.translate("DCMTreeForm", "Enter filter string", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&Help", None, -1))
        self.menu_Edit.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&Edit", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("DCMTreeForm", "toolBar", None, -1))
        self.action_Open.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Open", None, -1))
        self.action_Open.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Open dicom file", None, -1))
        self.action_Exit.setText(QtWidgets.QApplication.translate("DCMTreeForm", "E&xit", None, -1))
        self.action_Exit.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Exit program", None, -1))
        self.action_About.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&About", None, -1))
        self.action_Save.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Save", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Save &As", None, -1))
        self.actionSave_As.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Save DICOM file as", None, -1))
        self.action_Insert.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Insert", None, -1))
        self.action_Insert.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Insert DICOM tag", None, -1))
        self.action_Edit.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Edit", None, -1))
        self.action_Edit.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Change DICOM tag value", None, -1))
        self.action_Delete.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Delete", None, -1))
        self.action_Delete.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Delete DICOM tag", None, -1))
        self.actionSelect_All.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Select &All", None, -1))
        self.actionSelect_All.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Select all tags", None, -1))
        self.actionSelect_All.setShortcut(QtWidgets.QApplication.translate("DCMTreeForm", "Ctrl+A", None, -1))
        self.action_Copy.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Copy", None, -1))
        self.action_Copy.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Copy", None, -1))
        self.action_Copy.setShortcut(QtWidgets.QApplication.translate("DCMTreeForm", "Ctrl+C", None, -1))
        self.actionClear_selection.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Clear selection", None, -1))
        self.action_Find_tag.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Show &Filter bar", None, -1))

import dicomtreeQT5_rc
