# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dicomtreeQT5.ui'
##
## Created by: Qt User Interface Compiler version 5.15.10
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore

import dicomtreeQT5_rc

class Ui_DCMTreeForm(object):
    def setupUi(self, DCMTreeForm):
        if not DCMTreeForm.objectName():
            DCMTreeForm.setObjectName(u"DCMTreeForm")
        DCMTreeForm.resize(800, 600)
        DCMTreeForm.setAcceptDrops(True)
        self.action_Open = QAction(DCMTreeForm)
        self.action_Open.setObjectName(u"action_Open")
        icon = QIcon()
        icon.addFile(u":/icons/Icons/ImageOpen.xpm", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Exit = QAction(DCMTreeForm)
        self.action_Exit.setObjectName(u"action_Exit")
        icon1 = QIcon()
        icon1.addFile(u":/icons/Icons/exit.xpm", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_About = QAction(DCMTreeForm)
        self.action_About.setObjectName(u"action_About")
        self.action_Save = QAction(DCMTreeForm)
        self.action_Save.setObjectName(u"action_Save")
        icon2 = QIcon()
        icon2.addFile(u":/icons/Icons/ImageSave.xpm", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Save.setIcon(icon2)
        self.actionSave_As = QAction(DCMTreeForm)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As.setIcon(icon2)
        self.action_Insert = QAction(DCMTreeForm)
        self.action_Insert.setObjectName(u"action_Insert")
        icon3 = QIcon()
        icon3.addFile(u":/icons/Icons/Farm-Fresh_tag_blue_add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Insert.setIcon(icon3)
        self.action_Edit = QAction(DCMTreeForm)
        self.action_Edit.setObjectName(u"action_Edit")
        icon4 = QIcon()
        icon4.addFile(u":/icons/Icons/Farm-Fresh_tag_blue_edit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Edit.setIcon(icon4)
        self.action_Delete = QAction(DCMTreeForm)
        self.action_Delete.setObjectName(u"action_Delete")
        icon5 = QIcon()
        icon5.addFile(u":/icons/Icons/Farm-Fresh_tag_blue_delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Delete.setIcon(icon5)
        self.actionSelect_All = QAction(DCMTreeForm)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.action_Copy = QAction(DCMTreeForm)
        self.action_Copy.setObjectName(u"action_Copy")
        self.actionClear_selection = QAction(DCMTreeForm)
        self.actionClear_selection.setObjectName(u"actionClear_selection")
        self.action_Find_tag = QAction(DCMTreeForm)
        self.action_Find_tag.setObjectName(u"action_Find_tag")
        icon6 = QIcon()
        icon6.addFile(u":/icons/Icons/search.xpm", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Find_tag.setIcon(icon6)
        self.actionExpand_all = QAction(DCMTreeForm)
        self.actionExpand_all.setObjectName(u"actionExpand_all")
        self.actionCollapse_all = QAction(DCMTreeForm)
        self.actionCollapse_all.setObjectName(u"actionCollapse_all")
        self.centralwidget = QWidget(DCMTreeForm)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAcceptDrops(True)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(2, 2, -1, -1)
        self.fsearchbar = QFrame(self.centralwidget)
        self.fsearchbar.setObjectName(u"fsearchbar")
        self.fsearchbar.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fsearchbar.sizePolicy().hasHeightForWidth())
        self.fsearchbar.setSizePolicy(sizePolicy)
        self.fsearchbar.setMinimumSize(QSize(0, 32))
        self.fsearchbar.setMaximumSize(QSize(16777215, 32))
        self.fsearchbar.setFrameShape(QFrame.StyledPanel)
        self.fsearchbar.setFrameShadow(QFrame.Raised)
        self.layoutWidget = QWidget(self.fsearchbar)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(2, 2, 781, 34))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.qle_filter_tag = QLineEdit(self.layoutWidget)
        self.qle_filter_tag.setObjectName(u"qle_filter_tag")
        self.qle_filter_tag.setClearButtonEnabled(True)

        self.horizontalLayout.addWidget(self.qle_filter_tag)


        self.verticalLayout.addWidget(self.fsearchbar)

        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setFamily(u"Monospace")
        self.treeView.setFont(font)
        self.treeView.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.treeView.setAcceptDrops(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QAbstractItemView.DragDrop)
        self.treeView.setDefaultDropAction(Qt.CopyAction)
        self.treeView.setAlternatingRowColors(False)
        self.treeView.setSelectionMode(QAbstractItemView.MultiSelection)

        self.verticalLayout.addWidget(self.treeView)


        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        DCMTreeForm.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(DCMTreeForm)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 30))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        DCMTreeForm.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(DCMTreeForm)
        self.statusbar.setObjectName(u"statusbar")
        DCMTreeForm.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(DCMTreeForm)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(32, 32))
        DCMTreeForm.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_About)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menu_Edit.addAction(self.actionClear_selection)
        self.menu_Edit.addAction(self.actionExpand_all)
        self.menu_Edit.addAction(self.actionCollapse_all)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Find_tag)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Insert)
        self.menu_Edit.addAction(self.action_Edit)
        self.menu_Edit.addAction(self.action_Delete)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Insert)
        self.toolBar.addAction(self.action_Edit)
        self.toolBar.addAction(self.action_Delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Find_tag)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(DCMTreeForm)
        self.action_Exit.triggered.connect(DCMTreeForm.close)

        QMetaObject.connectSlotsByName(DCMTreeForm)
    # setupUi

    def retranslateUi(self, DCMTreeForm):
        DCMTreeForm.setWindowTitle(QCoreApplication.translate("DCMTreeForm", u"Dicom Tree Viewer", None))
        self.action_Open.setText(QCoreApplication.translate("DCMTreeForm", u"&Open", None))
#if QT_CONFIG(tooltip)
        self.action_Open.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Open dicom file", None))
#endif // QT_CONFIG(tooltip)
        self.action_Exit.setText(QCoreApplication.translate("DCMTreeForm", u"E&xit", None))
#if QT_CONFIG(tooltip)
        self.action_Exit.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Exit program", None))
#endif // QT_CONFIG(tooltip)
        self.action_About.setText(QCoreApplication.translate("DCMTreeForm", u"&About", None))
        self.action_Save.setText(QCoreApplication.translate("DCMTreeForm", u"&Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("DCMTreeForm", u"Save &As", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Save DICOM file as", None))
#endif // QT_CONFIG(tooltip)
        self.action_Insert.setText(QCoreApplication.translate("DCMTreeForm", u"&Insert", None))
#if QT_CONFIG(tooltip)
        self.action_Insert.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Insert DICOM tag", None))
#endif // QT_CONFIG(tooltip)
        self.action_Edit.setText(QCoreApplication.translate("DCMTreeForm", u"&Edit", None))
#if QT_CONFIG(tooltip)
        self.action_Edit.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Change DICOM tag value", None))
#endif // QT_CONFIG(tooltip)
        self.action_Delete.setText(QCoreApplication.translate("DCMTreeForm", u"&Delete", None))
#if QT_CONFIG(tooltip)
        self.action_Delete.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Delete DICOM tag", None))
#endif // QT_CONFIG(tooltip)
        self.actionSelect_All.setText(QCoreApplication.translate("DCMTreeForm", u"Select &all", None))
#if QT_CONFIG(tooltip)
        self.actionSelect_All.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Select all tags", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSelect_All.setShortcut(QCoreApplication.translate("DCMTreeForm", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_Copy.setText(QCoreApplication.translate("DCMTreeForm", u"&Copy", None))
#if QT_CONFIG(tooltip)
        self.action_Copy.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Copy", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Copy.setShortcut(QCoreApplication.translate("DCMTreeForm", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionClear_selection.setText(QCoreApplication.translate("DCMTreeForm", u"Clear selection", None))
        self.action_Find_tag.setText(QCoreApplication.translate("DCMTreeForm", u"Show &Filter bar", None))
        self.actionExpand_all.setText(QCoreApplication.translate("DCMTreeForm", u"E&xpand all", None))
#if QT_CONFIG(tooltip)
        self.actionExpand_all.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Expand all levels", None))
#endif // QT_CONFIG(tooltip)
        self.actionCollapse_all.setText(QCoreApplication.translate("DCMTreeForm", u"C&ollapse all", None))
#if QT_CONFIG(tooltip)
        self.actionCollapse_all.setToolTip(QCoreApplication.translate("DCMTreeForm", u"Collapse all levels", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("DCMTreeForm", u"Filter DICOM tags:", None))
        self.qle_filter_tag.setPlaceholderText(QCoreApplication.translate("DCMTreeForm", u"Enter filter string", None))
        self.menuFile.setTitle(QCoreApplication.translate("DCMTreeForm", u"&File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("DCMTreeForm", u"&Help", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("DCMTreeForm", u"&Edit", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("DCMTreeForm", u"toolBar", None))
    # retranslateUi

