# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dicomtreeQT5.ui',
# licensing of 'dicomtreeQT5.ui' applies.
#
# Created: Wed Sep 18 11:34:03 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DCMTreeForm(object):
    def setupUi(self, DCMTreeForm):
        DCMTreeForm.setObjectName("DCMTreeForm")
        DCMTreeForm.resize(800, 600)
        DCMTreeForm.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(DCMTreeForm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.treeView.setFont(font)
        self.treeView.setAcceptDrops(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        DCMTreeForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DCMTreeForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        DCMTreeForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DCMTreeForm)
        self.statusbar.setObjectName("statusbar")
        DCMTreeForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DCMTreeForm)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        DCMTreeForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtWidgets.QAction(DCMTreeForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/ImageOpen.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit = QtWidgets.QAction(DCMTreeForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/exit.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(DCMTreeForm)
        self.action_About.setObjectName("action_About")
        self.action_Save = QtWidgets.QAction(DCMTreeForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/ImageSave.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon2)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(DCMTreeForm)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_Insert = QtWidgets.QAction(DCMTreeForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/add.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Insert.setIcon(icon3)
        self.action_Insert.setObjectName("action_Insert")
        self.action_Edit = QtWidgets.QAction(DCMTreeForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/edit.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Edit.setIcon(icon4)
        self.action_Edit.setObjectName("action_Edit")
        self.action_Delete = QtWidgets.QAction(DCMTreeForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/del.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon5)
        self.action_Delete.setObjectName("action_Delete")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_About)
        self.menu_Edit.addAction(self.action_Insert)
        self.menu_Edit.addAction(self.action_Edit)
        self.menu_Edit.addAction(self.action_Delete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Insert)
        self.toolBar.addAction(self.action_Edit)
        self.toolBar.addAction(self.action_Delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(DCMTreeForm)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("triggered()"), DCMTreeForm.close)
        QtCore.QMetaObject.connectSlotsByName(DCMTreeForm)

    def retranslateUi(self, DCMTreeForm):
        DCMTreeForm.setWindowTitle(QtWidgets.QApplication.translate("DCMTreeForm", "Dicom Tree Viewer", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&Help", None, -1))
        self.menu_Edit.setTitle(QtWidgets.QApplication.translate("DCMTreeForm", "&Edit", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("DCMTreeForm", "toolBar", None, -1))
        self.action_Open.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Open", None, -1))
        self.action_Open.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Open dicom file", None, -1))
        self.action_Exit.setText(QtWidgets.QApplication.translate("DCMTreeForm", "E&xit", None, -1))
        self.action_Exit.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Exit program", None, -1))
        self.action_About.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&About", None, -1))
        self.action_Save.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Save", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("DCMTreeForm", "Save &As", None, -1))
        self.actionSave_As.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Save DICOM file as", None, -1))
        self.action_Insert.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Insert", None, -1))
        self.action_Insert.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Insert DICOM tag", None, -1))
        self.action_Edit.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Edit", None, -1))
        self.action_Edit.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Change DICOM tag value", None, -1))
        self.action_Delete.setText(QtWidgets.QApplication.translate("DCMTreeForm", "&Delete", None, -1))
        self.action_Delete.setToolTip(QtWidgets.QApplication.translate("DCMTreeForm", "Delete DICOM tag", None, -1))

import dicomtreeQT5_rc
